# Generated by Django 3.0.3 on 2020-03-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSuccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App', models.CharField(max_length=150)),
                ('Category', models.CharField(max_length=150)),
                ('Rating', models.IntegerField()),
                ('Reviews', models.IntegerField()),
                ('Size', models.IntegerField()),
                ('Type', models.IntegerField()),
                ('Price', models.IntegerField(verbose_name=0)),
                ('ContentRating', models.CharField(max_length=100)),
                ('Genres', models.CharField(max_length=100)),
                ('LastUpdated', models.CharField(max_length=100)),
                ('ContentVer', models.CharField(max_length=100)),
                ('AndroidVer', models.CharField(max_length=100)),
            ],
        ),
    ]
