# Generated by Django 3.0.3 on 2020-03-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200330_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsuccess',
            name='Category',
            field=models.CharField(choices=[('FAMILY', 'FAMILY'), ('GAME', 'GAME'), ('TOOLS', 'TOOLS'), ('MEDICAL', 'MEDICAL'), ('BUSINESS', 'BUSINESS'), ('PRODUCITVITY', 'PRODUCTIVITY'), ('PERSONALIZATION', 'PERSONALIZATION'), ('COMMUNICATION', 'COMMUNICATION'), ('SPORTS', 'SPORTS'), ('LIFESTYLE', 'LIFESTYLE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appsuccess',
            name='ContentRating',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Teen', 'Teen'), ('Everyone 10+', 'Everyone 10+'), ('Mature 17+', 'Mature 17+'), ('Adults only 18+', 'Adults only 18+'), ('Unrated', 'Unrated')], max_length=20),
        ),
    ]
