# Generated by Django 3.0.3 on 2020-03-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200331_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsuccess',
            name='Category',
            field=models.CharField(choices=[('FAMILY', 'FAMILY'), ('GAME', 'GAME'), ('TOOLS', 'TOOLS'), ('MEDICAL', 'MEDICAL'), ('BUSINESS', 'BUSINESS'), ('PRODUCTIVITY', 'PRODUCTIVITY'), ('PERSONALIZATION', 'PERSONALIZATION'), ('COMMUNICATION', 'COMMUNICATION'), ('SPORTS', 'SPORTS'), ('LIFESTYLE', 'LIFESTYLE')], max_length=20),
        ),
    ]
