# Generated by Django 3.0.3 on 2020-04-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200331_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsuccess',
            name='Category',
            field=models.CharField(choices=[('ART_AND_DESIGN', 'ART_AND_DESIGN'), ('AUTO_AND_VEHICLES', 'AUTO_AND_VEHICLES'), ('BEAUTY', 'BEAUTY'), ('COMICS', 'COMICS'), ('COMMUNICATION', 'COMMUNICATION'), ('EDUCATION', 'EDUCATION'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('FOOD_AND_DRINK', 'FOOD_AND_DRINK'), ('HOUSE_AND_HOME', 'HOUSE_AND_HOME'), ('LIBRARIES', 'LIBRARIES')], max_length=20),
        ),
    ]
